# Generated by Django 2.1.3 on 2021-12-16 19:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='kategoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='data utworzenia')),
            ],
            options={
                'verbose_name': 'post: Kategoria',
                'verbose_name_plural': 'posty: Kategorie',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('content', ckeditor.fields.RichTextField(verbose_name='treść')),
                ('image', imagekit.models.fields.ProcessedImageField(default='img/news/news_default.jpg', upload_to='img/news', verbose_name='zdjęcie')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data publikacji')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categories', models.ManyToManyField(related_name='get_posts', to='news.Category', verbose_name='kategoria')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posty',
                'ordering': ['-published'],
            },
        ),
    ]
