# Generated by Django 2.1.3 on 2018-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_price_list', models.CharField(max_length=100, verbose_name='Nazwa Cennika')),
            ],
            options={
                'verbose_name': 'Cennik - kategoria',
                'verbose_name_plural': 'Cenniki - kategorie',
            },
        ),
    ]
