# Generated by Django 2.1.3 on 2018-11-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='Usługa')),
                ('service_details', models.CharField(max_length=200, verbose_name='Szczegóły')),
                ('price', models.CharField(max_length=20, verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Ceny',
            },
        ),
        migrations.AddField(
            model_name='price_table',
            name='order',
            field=models.SmallIntegerField(null=True, verbose_name='Kolejność na stronie'),
        ),
        migrations.AddField(
            model_name='price',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.Price_table'),
        ),
    ]
