# Generated by Django 2.1.3 on 2018-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20181122_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='Usługa')),
                ('service_details', models.CharField(max_length=200, verbose_name='Szczegóły')),
                ('price', models.CharField(max_length=20, verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Ceny',
            },
        ),
        migrations.AlterModelOptions(
            name='price_table',
            options={'ordering': ['order'], 'verbose_name': 'Cennik - kategoria', 'verbose_name_plural': 'Cenniki - kategorie'},
        ),
        migrations.AlterField(
            model_name='price_table',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Kolejność na stronie'),
        ),
    ]
