# Generated by Django 2.1.3 on 2018-11-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_auto_20181122_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price_table',
            new_name='Price_list',
        ),
    ]
