# Generated by Django 2.1.3 on 2018-11-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_auto_20181122_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prices.Price_list'),
            preserve_default=False,
        ),
    ]
