# Generated by Django 2.1.3 on 2018-11-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_price_price_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_list',
        ),
    ]
