# Generated by Django 2.1.3 on 2018-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_price_price_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price_list', 'order'], 'verbose_name': 'Cena', 'verbose_name_plural': 'Ceny'},
        ),
        migrations.AddField(
            model_name='price',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Kolejność ceny w tabeli'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price_list',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Kolejność tabel'),
        ),
    ]
