# Generated by Django 2.1.3 on 2019-07-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0010_auto_20181122_1548'),
    ]

    operations = [
    	(migrations.RenameModel('Price_list', 'PriceList'))
    ]
