# Generated by Django 2.1.3 on 2019-07-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_auto_20190718_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price_list', 'order'], 'verbose_name': 'cena', 'verbose_name_plural': 'ceny'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['order'], 'verbose_name': 'cennik - kategoria', 'verbose_name_plural': 'cenniki - kategorie'},
        ),
        migrations.AlterField(
            model_name='price',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność ceny w tabeli'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=20, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.PriceList', verbose_name='cennik'),
        ),
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(max_length=200, verbose_name='usługa'),
        ),
        migrations.AlterField(
            model_name='price',
            name='service_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='szczegóły'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność tabel'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='title_price_list',
            field=models.CharField(max_length=100, verbose_name='nazwa cennika'),
        ),
    ]
