# Generated by Django 2.1.3 on 2019-07-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0012_auto_20190718_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='kolejność ceny w tabeli'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='kolejność tabel'),
            preserve_default=False,
        ),
    ]
