# Generated by Django 2.1.3 on 2018-11-22 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryportrait',
            name='image',
            field=models.ImageField(upload_to='img/portraits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='gallerystudio',
            name='image',
            field=models.ImageField(upload_to='img/studio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='galleryweddings',
            name='image',
            field=models.ImageField(upload_to='img/weddings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Plik'),
        ),
    ]
