# Generated by Django 2.1.3 on 2019-07-18 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181122_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryportrait',
            options={'ordering': ['order'], 'verbose_name': 'galeria - Fotografia Portretowa', 'verbose_name_plural': 'galeria - Fotografia Portretowa'},
        ),
        migrations.AlterModelOptions(
            name='gallerystudio',
            options={'ordering': ['order'], 'verbose_name': 'galeria - Studio', 'verbose_name_plural': 'galeria - Studio'},
        ),
        migrations.AlterModelOptions(
            name='galleryweddings',
            options={'ordering': ['order'], 'verbose_name': 'galeria - Fotografia Weselna', 'verbose_name_plural': 'galeria - Fotografia Weselna'},
        ),
        migrations.AlterField(
            model_name='galleryportrait',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='galleryportrait',
            name='image',
            field=models.ImageField(upload_to='img/portraits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='plik'),
        ),
        migrations.AlterField(
            model_name='galleryportrait',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność na stronie'),
        ),
        migrations.AlterField(
            model_name='galleryportrait',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='gallerystudio',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='gallerystudio',
            name='image',
            field=models.ImageField(upload_to='img/studio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='plik'),
        ),
        migrations.AlterField(
            model_name='gallerystudio',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność na stronie'),
        ),
        migrations.AlterField(
            model_name='gallerystudio',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='galleryweddings',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='galleryweddings',
            name='image',
            field=models.ImageField(upload_to='img/weddings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='plik'),
        ),
        migrations.AlterField(
            model_name='galleryweddings',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kolejność na stronie'),
        ),
        migrations.AlterField(
            model_name='galleryweddings',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tytuł'),
        ),
    ]
