# Generated by Django 2.1.3 on 2019-07-19 14:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190719_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoportrait',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='img/services/portrait/', verbose_name='zdjęcie'),
        ),
        migrations.AlterField(
            model_name='fotostudio',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='img/services/studio/', verbose_name='zdjęcie'),
        ),
        migrations.AlterField(
            model_name='fotowedding',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='img/services/wedding/', verbose_name='zdjęcie'),
        ),
    ]
