# Generated by Django 2.1.3 on 2021-12-16 19:26

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='imię')),
                ('job_title', models.CharField(max_length=200, verbose_name='stanowisko')),
                ('description', models.TextField(verbose_name='opis')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='img/about/', verbose_name='plik')),
                ('order', models.PositiveSmallIntegerField(verbose_name='kolejność na stronie')),
            ],
            options={
                'verbose_name': 'pracownik',
                'verbose_name_plural': 'pracownicy',
                'ordering': ['order'],
            },
        ),
    ]
