# Generated by Django 2.1.3 on 2018-11-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Imię')),
                ('job_title', models.CharField(max_length=200, verbose_name='Stanowisko')),
                ('description', models.TextField(verbose_name='Opis')),
                ('image', models.ImageField(upload_to='', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'pracownik',
                'verbose_name_plural': 'pracownicy',
            },
        ),
    ]
