# Generated by Django 2.1.3 on 2021-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='nazwa klucza')),
                ('name', models.CharField(max_length=200, verbose_name='sieć społecznościowa')),
                ('url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'linki',
                'ordering': ['name'],
            },
        ),
    ]
